import React from "react";
import NavBar from "@/components/NavBar/NavBar";
import ArticleAbout from "@/components/about/Article1";
import ArticleAbout2 from "@/components/about/Article2";
import ArticleAbout3 from "@/components/about/Article3";
import ArticleAbout4 from "@/components/about/Article4";
import Footer from "@/components/Footer";
import ArticleAbout5 from "@/components/about/Article5";
import ArticleAbout6 from "@/components/about/Article6";

export const metadata = {
  title: "ElectronPlayer | Sobre",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      <NavBar />
      <main>
        <ArticleAbout />
        <ArticleAbout2 />
        <ArticleAbout3 />
        <ArticleAbout4 />
        <ArticleAbout5 />
        <ArticleAbout6 />
      </main>
      <Footer />
    </>
  );
}

export default page;
