import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar/NavBar";
import Questions from "@/components/contact/Questions";
import React from "react";

export const metadata = {
  title: "ElectronPlayer | Soporte",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      <NavBar />
      <main>
        <Questions />
      </main>
      <Footer />
    </>
  );
}

export default page;
